sonar.projectKey=vulnerable-java-demo
sonar.projectName=Vulnerable Java Demo
sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.host.url=http://13.234.29.72:9000/
sonar.login=squ_fe690779020b51e41a4b4036a3a377b48f05782f
